defmodule NexusMCP.Server do
  @moduledoc """
  Behaviour for defining an MCP server.

  Supports the three MCP server primitives:

  - **Tools** — model-controlled functions (`deftool`)
  - **Prompts** — user-controlled message templates (`defprompt`)
  - **Resources** — application-controlled context (`defresource`, `defresource_template`)

  ## Usage

  ### Tools (DSL style)

      defmodule MyApp.MCP do
        use NexusMCP.Server,
          name: "my-app",
          version: "1.0.0"

        deftool "get_page", "Get a page by ID",
          params: [id: {:string!, "Page ID"}] do
          page = CMS.get_page!(params["id"])
          {:ok, Map.take(page, [:id, :title, :slug, :body])}
        end
      end

  ### Prompts

      defprompt "code_review", "Ask the model to review code",
        arguments: [code: {:string!, "The code to review"}] do
        {:ok, [
          %{role: "user", content: %{type: "text",
            text: "Please review this code:\\n" <> params["code"]}}
        ]}
      end

  ### Resources

      defresource "config://app",
        name: "app_config",
        description: "Application configuration",
        mime_type: "application/json" do
        {:ok, Jason.encode!(MyApp.config())}
      end

      defresource_template "file:///{path}",
        name: "project_files",
        description: "Files in the project directory",
        mime_type: "text/plain" do
        {:ok, File.read!(params["path"])}
      end

  ## Options

  - `:name` - Server name (required)
  - `:version` - Server version (required)
  - `:idle_timeout` - Session idle timeout in ms (default: 7_200_000 / 2 hours)
  """

  @type session :: %{
          session_id: String.t(),
          assigns: map()
        }

  @doc """
  Returns the list of tool definitions.
  """
  @callback tools() :: [map()]

  @doc """
  Handle a tool call. Receives the tool name, params, and session state.
  """
  @callback handle_tool_call(name :: String.t(), params :: map(), session :: session()) ::
              {:ok, term()} | {:error, String.t()}

  @doc """
  Returns the list of prompt definitions.
  """
  @callback prompts() :: [map()]

  @doc """
  Handle a `prompts/get` call. Receives the prompt name, arguments, and session.

  Should return `{:ok, messages}` where `messages` is a list of
  `%{role: "user" | "assistant", content: %{...}}` maps.
  """
  @callback handle_prompt_get(name :: String.t(), arguments :: map(), session :: session()) ::
              {:ok, [map()]} | {:error, String.t() | :not_found}

  @doc """
  Returns the list of static resource definitions.
  """
  @callback resources() :: [map()]

  @doc """
  Returns the list of resource template definitions.
  """
  @callback resource_templates() :: [map()]

  @doc """
  Handle a `resources/read` call. Receives the URI, the params captured from the
  URI template (empty map for static resources), and the session.

  Should return `{:ok, content}` where `content` is one of:

  - A string — wrapped as `text` if the resource's `mimeType` is textual,
    otherwise base64-encoded as `blob`
  - `%{text: string}` or `%{blob: base64}` — passed through

  Return `{:error, :not_found}` for unknown URIs.
  """
  @callback handle_resource_read(uri :: String.t(), params :: map(), session :: session()) ::
              {:ok, String.t() | map()} | {:error, String.t() | :not_found}

  @doc """
  Per-session initialization. Called when a new session is created.
  Receives the session map and should return `{:ok, session}` or `{:error, reason}`.
  """
  @callback init(session :: session()) :: {:ok, session()} | {:error, String.t()}

  @doc """
  Returns server info (name, version). Generated by `use NexusMCP.Server`.
  """
  @callback server_info() :: %{name: String.t(), version: String.t()}

  @doc """
  Returns the idle timeout in milliseconds.
  """
  @callback idle_timeout() :: non_neg_integer()

  @doc """
  Wraps every tool call execution. Runs in the Task process before the handler.
  Override to set up process-local state (e.g. tenant context) or rescue errors.

  Default implementation just calls `fun.()`.
  """
  @callback wrap_tool_call(session :: session(), fun :: (-> {:ok, term()} | {:error, String.t()})) ::
              {:ok, term()} | {:error, String.t()}

  defmacro __using__(opts) do
    name = Keyword.fetch!(opts, :name)
    version = Keyword.fetch!(opts, :version)
    idle_timeout = Keyword.get(opts, :idle_timeout, 7_200_000)

    quote do
      @behaviour NexusMCP.Server

      Module.register_attribute(__MODULE__, :__nexus_tools__, accumulate: true)
      Module.register_attribute(__MODULE__, :__nexus_prompts__, accumulate: true)
      Module.register_attribute(__MODULE__, :__nexus_resources__, accumulate: true)
      Module.register_attribute(__MODULE__, :__nexus_resource_templates__, accumulate: true)
      @before_compile NexusMCP.Server.Compile

      import NexusMCP.Server.Tool, only: [deftool: 3, deftool: 4, format_changeset_errors: 1]
      import NexusMCP.Server.Prompt, only: [defprompt: 3, defprompt: 4]

      import NexusMCP.Server.Resource,
        only: [defresource: 2, defresource: 3, defresource_template: 2, defresource_template: 3]

      @doc false
      @impl NexusMCP.Server
      def server_info do
        %{name: unquote(name), version: unquote(version)}
      end

      @doc false
      @impl NexusMCP.Server
      def idle_timeout do
        unquote(idle_timeout)
      end

      @impl NexusMCP.Server
      def init(session), do: {:ok, session}

      @impl NexusMCP.Server
      def wrap_tool_call(_session, fun), do: fun.()

      defoverridable init: 1, wrap_tool_call: 2

      # Defaults for tools/prompts/resources callbacks are injected by
      # `NexusMCP.Server.Compile.__before_compile__/1` so the DSL-generated
      # functions can override them. Putting them in this macro would shadow
      # the DSL output (defoverridable doesn't see `@before_compile` injections).
    end
  end
end
